### ISSUE TITLE
Issues with highlighting in Razor

### ISSUE THREAD

**Issue by sohcah** [barfurth/plastic-jetbrains#10]
In Rider, C# syntax within Razor pages doesn't get highlighted correctly with this theme enabled. The highlighting shows very briefly and then disappears, just becoming gray within the C# code sections.

**Comment by sbarfurth** [comment]
Hey @sohcah, C# is not explicitly supported yet. If you want, you can give me an example repository I could open in Rider and I may be able to fix this issue.

**Comment by sbarfurth** [comment]
I haven't heard back from you and this one is hard for me to do on my own. I've marked the issue stale for now, but I will be happy to check on it when you have time to provide some help.
