### ISSUE TITLE
Plugin incompatible with latest IntelliJ EAP (Build #IU-221.3427.89)

### ISSUE THREAD

**Issue by GavinRay97** [barfurth/plastic-jetbrains#5]
Hello, sorry to bother, but I really love this theme and the update released on the 26th unfortunately broke it.

I can see that in the `gradle.properties` file, there is a version range:
https://github.com/barfurth/plastic-jetbrains/blob/4413aad4d21184b7202d8fbdfe91d9429906a2ea/gradle.properties#L9-L12

To fix this, do I just need to modify the `pluginUntilBuild` to be `221.*` and rebuild?

Thank you =)

**Comment by GavinRay97** [comment]
Ah yes, it seems so!

I got it working again by opening the plugin `.jar` with 7zip, and editing `plugin.xml`:

![image](https://user-images.githubusercontent.com/26604994/151583846-ba274c88-70c5-4ae1-8095-67a7e216348a.png)

![image](https://user-images.githubusercontent.com/26604994/151583911-7316cb06-9e1f-4eb2-96ba-c1a50918b171.png)

**Comment by sbarfurth** [comment]
I will take a look tomorrow. Thanks for your PR!

**Comment by sbarfurth** [comment]
Fixed with 0.3.0

**Comment by sbarfurth** [comment]
Adding to this: Apparently you cannot unset the "until-build" property or else it is calculated as the "from-build" property with an additional asterisk. I've amended the "until-build" to 221.* and will be releasing that as 0.3.0. Very annoying...

**Comment by sbarfurth** [comment]
Version 0.3.0 is in approval and is marked compatible with the current EAP.
